// SPDX-FileCopyrightText: 2025 C. J. Howard
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <engine/scene/object.hpp>
#include <engine/scene/camera.hpp>
#include <engine/scene/collection.hpp>
#include <engine/render/operation.hpp>
#include <vector>

namespace engine::render
{
	/// Rendering context.
	struct context
	{
		/// Pointer to the camera.
		const scene::camera* camera;
	
		/// Collection of scene objects being rendered.
		scene::collection* collection;
	
		/// Current time, in seconds.
		float t;
	
		/// Timestep, in seconds.
		float dt;
	
		/// Subframe interpolation factor.
		float alpha;
	
		/// Objects visible to the active camera.
		std::vector<scene::object_base*> objects;
	
		/// Render operations generated by visible objects.
		std::vector<const operation*> operations;
	};
}
