// SPDX-FileCopyrightText: 2024 C. J. Howard
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef ANTKEEPER_MATERIAL_FLAGS_HPP
#define ANTKEEPER_MATERIAL_FLAGS_HPP

#define MATERIAL_FLAG_X_RAY 0x10
#define MATERIAL_FLAG_OUTLINE 0x20
#define MATERIAL_FLAG_VEGETATION 0x40
#define MATERIAL_FLAG_REFRACTIVE 0x80
#define MATERIAL_FLAG_DECAL 0x100
#define MATERIAL_FLAG_DECAL_SURFACE 0x200
#define MATERIAL_FLAG_WIREFRAME 0x80000000

#endif // ANTKEEPER_MATERIAL_FLAGS_HPP
