# SPDX-FileCopyrightText: 2024 C. J. Howard
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
    
    runs-on: ${{matrix.os}}-latest
    
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    
    - name: CMake configure
      run: cmake --preset ${{matrix.os}}-x64-release
    
    - name: Install glad requirements
      run: pip install -r build/${{matrix.os}}-x64/_deps/glad-src/requirements.txt
    
    - name: CMake build
      run: cmake --build --preset ${{matrix.os}}-x64-release
